// Data models for Alchemy Bioworksheet app
import 'package:cloud_firestore/cloud_firestore.dart';

class ProjectInfo {
  final int? id;
  final String projectName;
  final String? client;
  final DateTime date;
  final String? team;
  final String? remarks;

  ProjectInfo({
    this.id,
    required this.projectName,
    this.client,
    required this.date,
    this.team,
    this.remarks,
  });

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'projectName': projectName,
      'client': client,
      'date': date.millisecondsSinceEpoch,
      'team': team,
      'remarks': remarks,
    };
  }

  factory ProjectInfo.fromMap(Map<String, dynamic> map) {
    return ProjectInfo(
      id: map['id'],
      projectName: map['projectName'],
      client: map['client'],
      date: DateTime.fromMillisecondsSinceEpoch(map['date']),
      team: map['team'],
      remarks: map['remarks'],
    );
  }
}

class Sample {
  final int? id;
  final String? firebaseId; // Firebase document ID
  final int? orderId;
  final String stationId;
  final DateTime date;
  final double? lat;
  final double? lon;
  final String? habitat;
  final String? client;
  final String? biologistId;
  final String? remarks;
  final bool completed;
  final String sampleType; // Phytoplankton | Zooplankton | Macrobenthos
  final String? sampleMarking;
  final String? receiveId;
  final DateTime? analyzedDate;
  final String? deviceId; // Device that created this sample
  final DateTime? createdAt;
  final DateTime? updatedAt;
  final bool synced; // Whether synced to Firebase

  Sample({
    this.id,
    this.firebaseId,
    this.orderId,
    required this.stationId,
    required this.date,
    this.lat,
    this.lon,
    this.habitat,
    this.client,
    this.biologistId,
    this.remarks,
    this.completed = false,
    this.sampleType = 'Macrobenthos',
    this.sampleMarking,
    this.receiveId,
    this.analyzedDate,
    this.deviceId,
    this.createdAt,
    this.updatedAt,
    this.synced = false,
  });

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'firebaseId': firebaseId,
      'orderId': orderId,
      'stationId': stationId,
      'date': date.millisecondsSinceEpoch,
      'lat': lat,
      'lon': lon,
      'habitat': habitat,
      'client': client,
      'biologistId': biologistId,
      'remarks': remarks,
      'completed': completed ? 1 : 0,
      'sampleType': sampleType,
      'sampleMarking': sampleMarking,
      'receiveId': receiveId,
      'analyzedDate': analyzedDate?.millisecondsSinceEpoch,
      'deviceId': deviceId,
      'createdAt': createdAt?.millisecondsSinceEpoch,
      'updatedAt': updatedAt?.millisecondsSinceEpoch,
      'synced': synced ? 1 : 0,
    };
  }

  factory Sample.fromMap(Map<String, dynamic> map) {
    return Sample(
      id: map['id'],
      firebaseId: map['firebaseId'],
      orderId: map['orderId'],
      stationId: map['stationId'],
      date: DateTime.fromMillisecondsSinceEpoch(map['date']),
      lat: map['lat'],
      lon: map['lon'],
      habitat: map['habitat'],
      client: map['client'],
      biologistId: map['biologistId'],
      remarks: map['remarks'],
      completed: (map['completed'] ?? 0) == 1,
      sampleType: (map['sampleType'] ?? 'Macrobenthos') as String,
      sampleMarking: map['sampleMarking'],
      receiveId: map['receiveId'],
      analyzedDate: map['analyzedDate'] != null
          ? DateTime.fromMillisecondsSinceEpoch(map['analyzedDate'])
          : null,
      deviceId: map['deviceId'],
      createdAt: map['createdAt'] != null
          ? DateTime.fromMillisecondsSinceEpoch(map['createdAt'])
          : null,
      updatedAt: map['updatedAt'] != null
          ? DateTime.fromMillisecondsSinceEpoch(map['updatedAt'])
          : null,
      synced: (map['synced'] ?? 0) == 1,
    );
  }

  Map<String, dynamic> toFirestore() {
    return {
      'orderId': orderId,
      'stationId': stationId,
      'date': date.toIso8601String(),
      'lat': lat,
      'lon': lon,
      'habitat': habitat,
      'client': client,
      'biologistId': biologistId,
      'remarks': remarks,
      'completed': completed,
      'sampleType': sampleType,
      'sampleMarking': sampleMarking,
      'receiveId': receiveId, // Will be auto-generated by Firebase
      'analyzedDate': analyzedDate?.toIso8601String(),
      'deviceId': deviceId,
      'createdAt': (createdAt ?? DateTime.now()).toIso8601String(),
      'updatedAt': DateTime.now().toIso8601String(),
    };
  }

  factory Sample.fromFirestore(Map<String, dynamic> map, String docId) {
    // Helper to parse orderId from various types
    int? parseOrderId(dynamic value) {
      if (value == null) return null;
      if (value is int) return value;
      if (value is String) return int.tryParse(value);
      return null;
    }

    // Helper to parse DateTime from Timestamp or String
    DateTime parseDateTime(dynamic value) {
      if (value is Timestamp) return value.toDate();
      if (value is String) return DateTime.parse(value);
      throw ArgumentError('Cannot parse DateTime from type ${value.runtimeType}');
    }

    // Helper to parse optional DateTime from Timestamp or String
    DateTime? parseOptionalDateTime(dynamic value) {
      if (value == null) return null;
      if (value is Timestamp) return value.toDate();
      if (value is String) return DateTime.parse(value);
      return null;
    }

    return Sample(
      firebaseId: docId,
      orderId: parseOrderId(map['orderId']),
      stationId: map['stationId'] as String,
      date: parseDateTime(map['date']),
      lat: map['lat'] as double?,
      lon: map['lon'] as double?,
      habitat: map['habitat'] as String?,
      client: map['client'] as String?,
      biologistId: map['biologistId'] as String?,
      remarks: map['remarks'] as String?,
      completed: map['completed'] as bool? ?? false,
      sampleType: map['sampleType'] as String? ?? 'Macrobenthos',
      sampleMarking: map['sampleMarking'] as String?,
      receiveId: map['receiveId'] as String?,
      analyzedDate: parseOptionalDateTime(map['analyzedDate']),
      deviceId: map['deviceId'] as String?,
      createdAt: parseOptionalDateTime(map['createdAt']),
      updatedAt: parseOptionalDateTime(map['updatedAt']),
      synced: true,
    );
  }
}

class OrderInfo {
  final int? id;
  final String? firebaseId; // Firebase document ID
  final String clientName;
  final String? clientAddress;
  final String specimenType;
  final int numberOfSamples;
  final int? numberOfReplicates;
  final DateTime? dateReceived;
  final DateTime? dateAnalysis;
  final String? gearUsed;
  final String? areaOfGrab;
  final String? sieveSize;
  final String? netDiameter;
  final String? netMesh;
  final String? towType;
  final String? filteredVolume;
  final String? methodAnalysis;
  final String? reportNo;
  final String? referenceId;
  final String? comments;
  // New fields for reporting
  final String? sammNo;
  final String? authorizedBy;
  final String? institution;
  final String? sampleDescription;
  // Plankton calculation parameters
  final double? towDistance; // meters
  final double? sampleVolume; // ml
  final double? srCellVolume; // ml (Sedgewick-Rafter cell volume)
  final int? srCellsCounted; // number of SR cells counted
  // Firebase sync fields
  final String? deviceId; // Device that created this order
  final DateTime? createdAt;
  final DateTime? updatedAt;
  final bool synced; // Whether synced to Firebase

  OrderInfo({
    this.id,
    this.firebaseId,
    required this.clientName,
    this.clientAddress,
    required this.specimenType,
    required this.numberOfSamples,
    this.numberOfReplicates,
    this.dateReceived,
    this.dateAnalysis,
    this.gearUsed,
    this.areaOfGrab,
    this.sieveSize,
    this.netDiameter,
    this.netMesh,
    this.towType,
    this.filteredVolume,
    this.methodAnalysis,
    this.reportNo,
    this.referenceId,
    this.comments,
    this.sammNo,
    this.authorizedBy,
    this.institution,
    this.sampleDescription,
    this.towDistance,
    this.sampleVolume,
    this.srCellVolume,
    this.srCellsCounted,
    this.deviceId,
    this.createdAt,
    this.updatedAt,
    this.synced = false,
  });
  Map<String, dynamic> toMap() => {
    'id': id,
    'firebaseId': firebaseId,
    'clientName': clientName,
    'clientAddress': clientAddress,
    'specimenType': specimenType,
    'numberOfSamples': numberOfSamples,
    'numberOfReplicates': numberOfReplicates,
    'dateReceived': dateReceived?.millisecondsSinceEpoch,
    'dateAnalysis': dateAnalysis?.millisecondsSinceEpoch,
    'gearUsed': gearUsed,
    'areaOfGrab': areaOfGrab,
    'sieveSize': sieveSize,
    'netDiameter': netDiameter,
    'netMesh': netMesh,
    'towType': towType,
    'filteredVolume': filteredVolume,
    'methodAnalysis': methodAnalysis,
    'reportNo': reportNo,
    'referenceId': referenceId,
    'comments': comments,
    'sammNo': sammNo,
    'authorizedBy': authorizedBy,
    'institution': institution,
    'sampleDescription': sampleDescription,
    'towDistance': towDistance,
    'sampleVolume': sampleVolume,
    'srCellVolume': srCellVolume,
    'srCellsCounted': srCellsCounted,
    'deviceId': deviceId,
    'createdAt': createdAt?.millisecondsSinceEpoch,
    'updatedAt': updatedAt?.millisecondsSinceEpoch,
    'synced': synced ? 1 : 0,
  };

  factory OrderInfo.fromMap(Map<String, dynamic> m) => OrderInfo(
    id: m['id'] as int?,
    firebaseId: m['firebaseId'] as String?,
    clientName: m['clientName'] as String,
    clientAddress: m['clientAddress'] as String?,
    specimenType: m['specimenType'] as String,
    numberOfSamples: (m['numberOfSamples'] ?? 0) as int,
    numberOfReplicates: m['numberOfReplicates'] as int?,
    dateReceived: m['dateReceived'] != null
        ? DateTime.fromMillisecondsSinceEpoch(m['dateReceived'] as int)
        : null,
    dateAnalysis: m['dateAnalysis'] != null
        ? DateTime.fromMillisecondsSinceEpoch(m['dateAnalysis'] as int)
        : null,
    gearUsed: m['gearUsed'] as String?,
    areaOfGrab: m['areaOfGrab'] as String?,
    sieveSize: m['sieveSize'] as String?,
    netDiameter: m['netDiameter'] as String?,
    netMesh: m['netMesh'] as String?,
    towType: m['towType'] as String?,
    filteredVolume: m['filteredVolume'] as String?,
    methodAnalysis: m['methodAnalysis'] as String?,
    reportNo: m['reportNo'] as String?,
    referenceId: m['referenceId'] as String?,
    comments: m['comments'] as String?,
    sammNo: m['sammNo'] as String?,
    authorizedBy: m['authorizedBy'] as String?,
    institution: m['institution'] as String?,
    sampleDescription: m['sampleDescription'] as String?,
    towDistance: m['towDistance'] as double?,
    sampleVolume: m['sampleVolume'] as double?,
    srCellVolume: m['srCellVolume'] as double?,
    srCellsCounted: m['srCellsCounted'] as int?,
    deviceId: m['deviceId'] as String?,
    createdAt: m['createdAt'] != null
        ? DateTime.fromMillisecondsSinceEpoch(m['createdAt'] as int)
        : null,
    updatedAt: m['updatedAt'] != null
        ? DateTime.fromMillisecondsSinceEpoch(m['updatedAt'] as int)
        : null,
    synced: (m['synced'] ?? 0) == 1,
  );

  Map<String, dynamic> toFirestore() => {
    'clientName': clientName,
    'clientAddress': clientAddress,
    'specimenType': specimenType,
    'numberOfSamples': numberOfSamples,
    'numberOfReplicates': numberOfReplicates,
    'dateReceived': dateReceived?.toIso8601String(),
    'dateAnalysis': dateAnalysis?.toIso8601String(),
    'gearUsed': gearUsed,
    'areaOfGrab': areaOfGrab,
    'sieveSize': sieveSize,
    'netDiameter': netDiameter,
    'netMesh': netMesh,
    'towType': towType,
    'filteredVolume': filteredVolume,
    'methodAnalysis': methodAnalysis,
    'reportNo': reportNo,
    'referenceId': referenceId,
    'comments': comments,
    'sammNo': sammNo,
    'authorizedBy': authorizedBy,
    'institution': institution,
    'sampleDescription': sampleDescription,
    'towDistance': towDistance,
    'sampleVolume': sampleVolume,
    'srCellVolume': srCellVolume,
    'srCellsCounted': srCellsCounted,
    'deviceId': deviceId,
    'createdAt': (createdAt ?? DateTime.now()).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  };

  factory OrderInfo.fromFirestore(Map<String, dynamic> m, String docId) {
    // Helper to parse DateTime from Timestamp or String
    DateTime? parseDateTime(dynamic value) {
      if (value == null) return null;
      if (value is Timestamp) return value.toDate();
      if (value is String) return DateTime.parse(value);
      return null;
    }

    return OrderInfo(
      firebaseId: docId,
      clientName: m['clientName'] as String,
      clientAddress: m['clientAddress'] as String?,
      specimenType: m['specimenType'] as String,
      numberOfSamples: (m['numberOfSamples'] ?? 0) as int,
      numberOfReplicates: m['numberOfReplicates'] as int?,
      dateReceived: parseDateTime(m['dateReceived']),
      dateAnalysis: parseDateTime(m['dateAnalysis']),
      gearUsed: m['gearUsed'] as String?,
      areaOfGrab: m['areaOfGrab'] as String?,
      sieveSize: m['sieveSize'] as String?,
      netDiameter: m['netDiameter'] as String?,
      netMesh: m['netMesh'] as String?,
      towType: m['towType'] as String?,
      filteredVolume: m['filteredVolume'] as String?,
      methodAnalysis: m['methodAnalysis'] as String?,
      reportNo: m['reportNo'] as String?,
      referenceId: m['referenceId'] as String?,
      comments: m['comments'] as String?,
      sammNo: m['sammNo'] as String?,
      authorizedBy: m['authorizedBy'] as String?,
      institution: m['institution'] as String?,
      sampleDescription: m['sampleDescription'] as String?,
      towDistance: m['towDistance'] as double?,
      sampleVolume: m['sampleVolume'] as double?,
      srCellVolume: m['srCellVolume'] as double?,
      srCellsCounted: m['srCellsCounted'] as int?,
      deviceId: m['deviceId'] as String?,
      createdAt: parseDateTime(m['createdAt']),
      updatedAt: parseDateTime(m['updatedAt']),
      synced: true,
    );
  }
}

class Taxon {
  final int? id;
  final int? parentId;
  final String name;
  final String? rank;
  final String? notes;
  final String? specimenType; // Phytoplankton | Zooplankton | Macrobenthos

  Taxon({
    this.id,
    this.parentId,
    required this.name,
    this.rank,
    this.notes,
    this.specimenType,
  });

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'parentId': parentId,
      'name': name,
      'rank': rank,
      'notes': notes,
      'specimenType': specimenType,
    };
  }

  factory Taxon.fromMap(Map<String, dynamic> map) {
    return Taxon(
      id: map['id'],
      parentId: map['parentId'],
      name: map['name'],
      rank: map['rank'],
      notes: map['notes'],
      specimenType: map['specimenType'],
    );
  }

  // Helper method to check if this taxon is a leaf (has no children)
  bool get isLeaf => false; // This will be determined by the tree structure

  // Helper method to check if this taxon is a root (has no parent)
  bool get isRoot => parentId == null;
}

class CountRecord {
  final int? id;
  final int sampleId;
  final int taxonId;
  final int count;
  final String? note;
  final String? photoPath;

  CountRecord({
    this.id,
    required this.sampleId,
    required this.taxonId,
    required this.count,
    this.note,
    this.photoPath,
  });

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'sampleId': sampleId,
      'taxonId': taxonId,
      'count': count,
      'note': note,
      'photoPath': photoPath,
    };
  }

  factory CountRecord.fromMap(Map<String, dynamic> map) {
    return CountRecord(
      id: map['id'],
      sampleId: map['sampleId'],
      taxonId: map['taxonId'],
      count: map['count'],
      note: map['note'],
      photoPath: map['photoPath'],
    );
  }
}

class PendingChange {
  final int? id;
  final String changeType; // 'create', 'update', 'delete'
  final String specimenType;
  final int? taxonId;
  final String? oldData; // JSON string of old taxon data
  final String? newData; // JSON string of new taxon data
  final DateTime timestamp;
  final String? deviceId;
  final bool synced;

  PendingChange({
    this.id,
    required this.changeType,
    required this.specimenType,
    this.taxonId,
    this.oldData,
    this.newData,
    required this.timestamp,
    this.deviceId,
    this.synced = false,
  });

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'changeType': changeType,
      'specimenType': specimenType,
      'taxonId': taxonId,
      'oldData': oldData,
      'newData': newData,
      'timestamp': timestamp.millisecondsSinceEpoch,
      'deviceId': deviceId,
      'synced': synced ? 1 : 0,
    };
  }

  factory PendingChange.fromMap(Map<String, dynamic> map) {
    return PendingChange(
      id: map['id'],
      changeType: map['changeType'],
      specimenType: map['specimenType'],
      taxonId: map['taxonId'],
      oldData: map['oldData'],
      newData: map['newData'],
      timestamp: DateTime.fromMillisecondsSinceEpoch(map['timestamp']),
      deviceId: map['deviceId'],
      synced: (map['synced'] ?? 0) == 1,
    );
  }

  Map<String, dynamic> toFirestore() {
    return {
      'changeType': changeType,
      'specimenType': specimenType,
      'taxonId': taxonId,
      'oldData': oldData,
      'newData': newData,
      'timestamp': timestamp.toIso8601String(),
      'deviceId': deviceId,
      'status': 'pending', // pending, approved, rejected
    };
  }
}

/// Model for analysis results to be uploaded to Firebase
class AnalysisResult {
  final String? id; // Firebase document ID
  final int orderId;
  final int sampleId;
  final String stationId;
  final String specimenType;
  final String biologistId;
  final DateTime analyzedDate;
  final String deviceId;
  final List<TaxonCount> counts;
  final bool uploaded;
  final DateTime? uploadedAt;

  // Order metadata for reporting
  final String clientName;
  final String? clientAddress;
  final String? sammNo;
  final String? authorizedBy;
  final String? institution;
  final String? reportNo;
  final String? referenceId;
  final DateTime? dateReceived;

  // Calculation parameters
  final double? areaOfGrab; // m² for macrobenthos
  final double? filteredVolume; // L for plankton
  final double? dilutionFactor; // for plankton

  AnalysisResult({
    this.id,
    required this.orderId,
    required this.sampleId,
    required this.stationId,
    required this.specimenType,
    required this.biologistId,
    required this.analyzedDate,
    required this.deviceId,
    required this.counts,
    this.uploaded = false,
    this.uploadedAt,
    required this.clientName,
    this.clientAddress,
    this.sammNo,
    this.authorizedBy,
    this.institution,
    this.reportNo,
    this.referenceId,
    this.dateReceived,
    this.areaOfGrab,
    this.filteredVolume,
    this.dilutionFactor,
  });

  Map<String, dynamic> toFirestore() {
    return {
      'orderId': orderId,
      'sampleId': sampleId,
      'stationId': stationId,
      'specimenType': specimenType,
      'biologistId': biologistId,
      'analyzedDate': analyzedDate.toIso8601String(),
      'deviceId': deviceId,
      'counts': counts.map((c) => c.toMap()).toList(),
      'uploadedAt': DateTime.now().toIso8601String(),
      'clientName': clientName,
      'clientAddress': clientAddress,
      'sammNo': sammNo,
      'authorizedBy': authorizedBy,
      'institution': institution,
      'reportNo': reportNo,
      'referenceId': referenceId,
      'dateReceived': dateReceived?.toIso8601String(),
      'areaOfGrab': areaOfGrab,
      'filteredVolume': filteredVolume,
      'dilutionFactor': dilutionFactor,
    };
  }

  factory AnalysisResult.fromFirestore(Map<String, dynamic> m, String docId) {
    return AnalysisResult(
      id: docId,
      orderId: m['orderId'] as int,
      sampleId: m['sampleId'] as int,
      stationId: m['stationId'] as String,
      specimenType: m['specimenType'] as String,
      biologistId: m['biologistId'] as String,
      analyzedDate: DateTime.parse(m['analyzedDate'] as String),
      deviceId: m['deviceId'] as String,
      counts: (m['counts'] as List<dynamic>)
          .map((c) => TaxonCount.fromMap(c as Map<String, dynamic>))
          .toList(),
      uploaded: true,
      uploadedAt: m['uploadedAt'] != null
          ? DateTime.parse(m['uploadedAt'] as String)
          : null,
      clientName: m['clientName'] as String,
      clientAddress: m['clientAddress'] as String?,
      sammNo: m['sammNo'] as String?,
      authorizedBy: m['authorizedBy'] as String?,
      institution: m['institution'] as String?,
      reportNo: m['reportNo'] as String?,
      referenceId: m['referenceId'] as String?,
      dateReceived: m['dateReceived'] != null
          ? DateTime.parse(m['dateReceived'] as String)
          : null,
      areaOfGrab: m['areaOfGrab'] as double?,
      filteredVolume: m['filteredVolume'] as double?,
      dilutionFactor: m['dilutionFactor'] as double?,
    );
  }
}

/// Individual taxon count within an analysis result
class TaxonCount {
  final int taxonId;
  final String taxonName;
  final String? taxonRank;
  final List<String> hierarchy; // Full taxonomic hierarchy
  final int count;
  final double? density; // Calculated density (ind/m² or units/L)
  final String? note;

  TaxonCount({
    required this.taxonId,
    required this.taxonName,
    this.taxonRank,
    required this.hierarchy,
    required this.count,
    this.density,
    this.note,
  });

  Map<String, dynamic> toMap() {
    return {
      'taxonId': taxonId,
      'taxonName': taxonName,
      'taxonRank': taxonRank,
      'hierarchy': hierarchy,
      'count': count,
      'density': density,
      'note': note,
    };
  }

  factory TaxonCount.fromMap(Map<String, dynamic> m) {
    return TaxonCount(
      taxonId: m['taxonId'] as int,
      taxonName: m['taxonName'] as String,
      taxonRank: m['taxonRank'] as String?,
      hierarchy: (m['hierarchy'] as List<dynamic>).cast<String>(),
      count: m['count'] as int,
      density: m['density'] as double?,
      note: m['note'] as String?,
    );
  }
}
