// ==================== Report Log Section ====================

// DOM Elements for Report Log
const reportLogList = document.getElementById('report-log-list');
const logCountSpan = document.getElementById('log-count');
const logClientFilter = document.getElementById('log-client-filter');
const logDateFrom = document.getElementById('log-date-from');
const logDateTo = document.getElementById('log-date-to');
const logSearchBtn = document.getElementById('log-search-btn');
const logClearBtn = document.getElementById('log-clear-btn');
const exportLogBtn = document.getElementById('export-log-btn');

let reportLogs = [];

// Load Report Logs from Firestore
async function loadReportLogs() {
    reportLogList.innerHTML = '<p class="loading">Loading report logs...</p>';

    try {
        let query = db.collection('report_logs').orderBy('dateGenerated', 'desc');

        // Apply filters
        const clientFilter = logClientFilter.value.trim();
        if (clientFilter) {
            query = query.where('clientName', '==', clientFilter);
        }

        const snapshot = await query.get();
        reportLogs = snapshot.docs.map(doc => ({
            id: doc.id,
            ...doc.data()
        }));

        // Apply date filtering (client-side since Firestore has limitations)
        const dateFrom = logDateFrom.value ? new Date(logDateFrom.value) : null;
        const dateTo = logDateTo.value ? new Date(logDateTo.value) : null;

        if (dateFrom || dateTo) {
            reportLogs = reportLogs.filter(log => {
                const logDate = log.dateGenerated?.toDate() || new Date(log.dateGenerated);
                if (dateFrom && logDate < dateFrom) return false;
                if (dateTo && logDate > dateTo) return false;
                return true;
            });
        }

        displayReportLogs();
    } catch (error) {
        console.error('Error loading report logs:', error);
        reportLogList.innerHTML = '<p class="error">Error loading report logs. Please try again.</p>';
    }
}

// Display Report Logs in Table
function displayReportLogs() {
    logCountSpan.textContent = `${reportLogs.length} log${reportLogs.length !== 1 ? 's' : ''}`;

    if (reportLogs.length === 0) {
        reportLogList.innerHTML = '<p>No report logs found.</p>';
        return;
    }

    let html = `
        <table class="report-log-table">
            <thead>
                <tr>
                    <th>Date Generated</th>
                    <th>Client</th>
                    <th>Institution</th>
                    <th>Reference ID</th>
                    <th>Report Cover</th>
                    <th>Date Received</th>
                    <th>Num Samples</th>
                    <th>Report Type</th>
                    <th>Generated By</th>
                </tr>
            </thead>
            <tbody>
    `;

    reportLogs.forEach(log => {
        const dateGenerated = log.dateGenerated?.toDate ? log.dateGenerated.toDate() : new Date(log.dateGenerated);
        const dateReceived = log.dateReceived ? (log.dateReceived.toDate ? log.dateReceived.toDate() : new Date(log.dateReceived)) : null;

        html += `
            <tr>
                <td>${dateGenerated.toLocaleString('en-GB')}</td>
                <td>${log.clientName || 'N/A'}</td>
                <td>${log.institution || 'N/A'}</td>
                <td>${log.referenceId || 'N/A'}</td>
                <td>${log.reportCover || 'N/A'}</td>
                <td>${dateReceived ? dateReceived.toLocaleDateString('en-GB') : 'N/A'}</td>
                <td>${log.numberOfSamples || 0}</td>
                <td>${log.reportType || 'N/A'}</td>
                <td>${log.generatedBy || 'N/A'}</td>
            </tr>
        `;
    });

    html += `
            </tbody>
        </table>
    `;

    reportLogList.innerHTML = html;
}

// Save Report Log to Firestore
async function saveReportLog(logData) {
    try {
        const user = auth.currentUser;
        const reportLog = {
            clientName: logData.clientName,
            institution: logData.institution,
            referenceId: logData.referenceId,
            reportCover: logData.reportCover,
            dateReceived: logData.dateReceived,
            dateGenerated: firebase.firestore.FieldValue.serverTimestamp(),
            numberOfSamples: logData.numberOfSamples,
            reportType: logData.reportType, // 'Excel' or 'PDF'
            generatedBy: user ? user.email : 'unknown',
            specimenType: logData.specimenType
        };

        await db.collection('report_logs').add(reportLog);
        console.log('Report log saved successfully');
    } catch (error) {
        console.error('Error saving report log:', error);
    }
}

// Export Report Logs to CSV
function exportReportLogs() {
    if (reportLogs.length === 0) {
        alert('No logs to export');
        return;
    }

    const headers = ['Date Generated', 'Client', 'Institution', 'Reference ID', 'Report Cover', 'Date Received', 'Num Samples', 'Report Type', 'Generated By'];
    const rows = reportLogs.map(log => {
        const dateGenerated = log.dateGenerated?.toDate ? log.dateGenerated.toDate() : new Date(log.dateGenerated);
        const dateReceived = log.dateReceived ? (log.dateReceived.toDate ? log.dateReceived.toDate() : new Date(log.dateReceived)) : null;

        return [
            dateGenerated.toLocaleString('en-GB'),
            log.clientName || '',
            log.institution || '',
            log.referenceId || '',
            log.reportCover || '',
            dateReceived ? dateReceived.toLocaleDateString('en-GB') : '',
            log.numberOfSamples || 0,
            log.reportType || '',
            log.generatedBy || ''
        ];
    });

    let csvContent = headers.join(',') + '\n';
    rows.forEach(row => {
        csvContent += row.map(cell => `"${cell}"`).join(',') + '\n';
    });

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', `report_logs_${new Date().toISOString().split('T')[0]}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
}

// Event Listeners for Report Log Page
logSearchBtn.addEventListener('click', loadReportLogs);
logClearBtn.addEventListener('click', () => {
    logClientFilter.value = '';
    logDateFrom.value = '';
    logDateTo.value = '';
    loadReportLogs();
});
exportLogBtn.addEventListener('click', exportReportLogs);
